### ISSUE TITLE
No protection option for item drops on an existing claim

### ISSUE THREAD

**Issue by rosewritescode** [Redempt/RedClaims#2]
Suggesting the addition of a protection encompassing picking up items dropped on a user's claim.

**Comment by Redempt** [comment]
Not sure how I feel about this because it could deny drops from monsters you fought and killed on a claim

**Comment by rosa-xo** [comment]
But you could also afk in someone's mob farm and collect their drops for example. Maybe add a protection node for drops but allow anyone to pick up drops from monsters players kill?
